<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <MonoGamePlatform>Android</MonoGamePlatform>

        <TargetFramework>net10.0-android</TargetFramework>
        <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
        <OutputType>Exe</OutputType>
        <ApplicationId>com.companyname.Xitira.GamePadTester.And</ApplicationId>
        <ApplicationVersion>6</ApplicationVersion>
        <ApplicationDisplayVersion>1.6</ApplicationDisplayVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="MonoGame.Framework.Android" Version="3.8.5" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Xitira.GamePadTester\Xitira.GamePadTester.csproj" />
    </ItemGroup>


    <ItemGroup>
        <EmbeddedResource Include="../Xitira.GamePadTester.Content/ContentAND/Content.db">
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <TrimmerRootAssembly Include="LiteDB" />
    </ItemGroup>


</Project>